using Azure.Data.Tables;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;
using User_API.Models;

namespace User_API;

// Function 1 accepts user info as JSON and stores it in Azure Table Storage
// <!-- Microsoft Learn, 2024 [1] -->
// <!-- Azure Functions HTTP trigger is learned and used from Microsoft Learn -->
public class Function1
{
    private readonly ILogger<Function1> _logger;
    private readonly TableServiceClient _tableServiceClient;


    public Function1(ILogger<Function1> logger, TableServiceClient tableServiceClient)
    {
        _logger = logger;
        _tableServiceClient = tableServiceClient;
        tableServiceClient.CreateTableIfNotExists("User");
    }

    [Function("CreateUser")]
    public IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = "users")] HttpRequest req)
    {
        try
        {
            _logger.LogInformation("C# HTTP trigger CreateUser function processed a request.");
            var body = req.Body;

            var user = System.Text.Json.JsonSerializer.Deserialize<User>(body);

            // Basic validation (checks for the valid Id, generated by the server)
            // <!-- Microsoft Learn, 2024 [2] -->
            // <!--  was learned, gathered and used from Microsoft Learn for validation -->
            if (user is null)
            {
                return new BadRequestObjectResult(new { message = "Request body could not be read. Check your JSON." });
            }


            // Server generates the Id, meaning that the client should not send an id
            // <!-- Microsoft Learn, 2024 [3] -->
            // <!--  was learned, gathered and used from Microsoft Learn -->
            user.Id = Guid.NewGuid().ToString();
            user.PartitionKey = "User";
            user.RowKey = user.Id;

            var tableClient = _tableServiceClient.GetTableClient("User");
            tableClient.AddEntity(user);

            return new OkObjectResult(new {message = "User saved", id = user.Id});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating the user.");
            return new ObjectResult(new { message = "Application Error" }) { StatusCode = 500 };
        }
    }
}


// <!-- REFERENCE LIST -->
// -----------------------------
// <!-- Microsoft Learn. 2024[1]. Azure Functions HTTP trigger, Azure Functions [Online]. Available at: <https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-csharp> [Accessed 8 August 2026]. -->
// <!-- Microsoft Learn. 2024[2]. , Azure Functions [Online]. Available at:  [Accessed 8 August 2026]. -->
// <!-- Microsoft Learn. 2024[3]. , Azure Functions [Online]. Available at:  [Accessed 8 August 2026]. -->
